### ISSUE TITLE
Re-building the parser can fail

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#277]
**Describe the bug**
Building the parser sometimes fail. We should be able to rebuild the parser (e.g., to handle changes to the grammar). It seems to indicate the internals of the parser generation keeps some state when it shouldn't.

**To Reproduce**

Tested internally by calling `buildParser` twice in the `parsermanager`:
```
    /**
     * Build the parser
     */
    testBuildParser() {
        if (!this.templateMark) {
            const tokenStream = templateToTokens(this.template);
            const template = tokensToUntypedTemplateMark(tokenStream, this.templateKind);
            this.templateMark = templateMarkTyping(template, this.modelManager, this.templateKind);
        }
        this.parser = this.parserVisitor.toParser(this,this.templateMark,this.parsingTable);
    }

    /**
     * Build the parser
     */
    buildParser() {
        this.testBuildParser();
        this.testBuildParser();
    }
```

This results in some errors in a few tests:
```
  2) #TemplateMarkTransformer [Parse Success]
       #latedeliveryandpenalty
         should parse sample:
     TypeError: Cannot read property 'map' of undefined
      at result (lib/toparserrules.js:73:38)
      at P.seqMap.apply.parsers.map.x (lib/combinators.js:257:57)
      at Array.map (<anonymous>)
      at /Users/jeromesimeon/git/markdown-transform/packages/markdown-template/lib/combinators.js:257:48
      at parameters.result (lib/ToParserVisitor.js:39:16)
      at P.seqMap.apply.parsers.map.x (lib/combinators.js:257:57)
      at Array.map (<anonymous>)
      at /Users/jeromesimeon/git/markdown-transform/packages/markdown-template/lib/combinators.js:257:48
      at Object.org.accordproject.cicero.contract.AccordParty (lib/parsingtable.js:105:47)
      at func (/Users/jeromesimeon/git/markdown-transform/node_modules/parsimmon/src/parsimmon.js:803:30)
      at Parsimmon._ (/Users/jeromesimeon/git/markdown-transform/node_modules/parsimmon/src/parsimmon.js:1283:16)
      at Parsimmon._ (/Users/jeromesimeon/git/markdown-transform/node_modules/parsimmon/src/parsimmon.js:1017:23)
      at Parsimmon._ (/Users/jeromesimeon/git/markdown-transform/node_modules/parsimmon/src/parsimmon.js:717:40)
      at Parsimmon._ (/Users/jeromesimeon/git/markdown-transform/node_modules/parsimmon/src/parsimmon.js:1017:23)
      at Parsimmon._ (/Users/jeromesimeon/git/markdown-transform/node_modules/parsimmon/src/parsimmon.js:1017:23)
```

**Additional context**
This will affect editors (e.g., VSCode extension or Template Studio) or users relying on the API and expecting consistent behaviour when rebuilding the parser for a template.

**Comment by jeromesimeon** [comment]
Fixed in #278
