### ISSUE TITLE
Cannot install Markdown Transform 0.7.0

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/markdown-transform#96]
The latest `0.7.0` does not install due to the structure of the build with the new external model scripts.

```
bash-3.2$ npm install -g @accordproject/markdown-cli@0.7.0
/Users/jeromesimeon/.nvm/versions/node/v8.12.0/bin/markus -> /Users/jeromesimeon/.nvm/versions/node/v8.12.0/lib/node_modules/@accordproject/markdown-cli/index.js

> @accordproject/markdown-common@0.7.0 postinstall /Users/jeromesimeon/.nvm/versions/node/v8.12.0/lib/node_modules/@accordproject/markdown-cli/node_modules/@accordproject/markdown-common
> node ./scripts/getExternalModels.js

module.js:550
    throw err;
    ^

Error: Cannot find module '/Users/jeromesimeon/.nvm/versions/node/v8.12.0/lib/node_modules/@accordproject/markdown-cli/node_modules/@accordproject/markdown-common/scripts/getExternalModels.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @accordproject/markdown-common@0.7.0 postinstall: `node ./scripts/getExternalModels.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @accordproject/markdown-common@0.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeromesimeon/.npm/_logs/2019-10-26T18_52_10_502Z-debug.log
```

**Comment by jeromesimeon** [comment]
Fixed in PR #95
